# Your database type
# - SQLITE local storage (default)
# - MYSQL
# - MARIADB
# - MONGODB (Recommended)
database-type: SQLITE

# Print all operations inside the database in the console with the value formatted as Json
debug-mode: false

# The number of thread that will be used for your async database call
# If you are using MySQL, I would advice to set the same number as "minimum idle connection"
# In the case were you have more than 3 running operation, extra thread will be created temporarily
idle-thread-pool-size: 3

database:
  mysql:

    # Full host path containing host:port/database_name
    # exemple: jdbc:mysql://localhost:3306/ndatabase
    host: 'jdbc:mysql://localhost:3306/your_database_name'
    user: ''
    pass: ''

    # default com.mysql.jdbc.Driver
    driver-class-name: 'com.mysql.jdbc.Driver'

    # Set the minimum constantly opened connection with your database
    # note that the number of plugin won't multiply this number
    # so you can config this number according to your needs
    minimum-idle-connection: 3

    # Maximum number of connection in the pool
    maximum-pool-size: 10
  mariadb:

    # Full host path containing host:port/database_name
    # exemple: jdbc:mysql://localhost:3306/ndatabase
    host: 'jdbc:mysql://localhost:3306/your_database_name'
    user: ''
    pass: ''

    # default org.mariadb.jdbc.Driver
    driver-class-name: 'org.mariadb.jdbc.Driver'

    # Set the minimum constantly opened connection with your database
    # note that the number of plugin won't multiply this number
    # so you can config this number according to your needs
    minimum-idle-connection: 3

    # Maximum number of connection in the pool
    maximum-pool-size: 10
  sqlite:

    # File generated in your plugins/NDatabase/sqlite folder that will contain your database
    file-name: 'ndatabase.sqlite'

  mongodb:

    host: 'localhost'

    # Database name
    database: 'ndatabase'
    port: 27017
    user: ''
    pass: ''

# Cache settings
cache:
  # The minutes to expire the object after accessing it from the cache
  # When expired, the object will be committed to the database
  expire-after-access-minutes: 30

  # The maximum objects stored in the cache
  maximum-size: 10000

  # The timeout in seconds of getting an item in the cache
  get-timeout-seconds: 5

  # Changing the values to soft-references in the cache, allowing for purging of the values in a GC cycle
  # This should be enabled if you have problems with memory
  enable-soft-values: false

  # Refreshes the value from the database asynchronously after writing
  enable-refresh-after-write: false

  # The amount of minutes after a write to refresh
  refresh-after-write-minutes: 30

  # Collects statistics about the cache
  enable-stats: false